---
- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    ansible.builtin.apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
#    when: ansible_distribution == "ubuntu"


# Fedora

  - name: install httpd package
    ansible.builtin.dnf:
      name: 
       - httpd
       - php
      state: latest
      update_cache: yes
 #   when: ansible_distribution == "Fedora"

