---
- hosts: all
  become: true
  tasks:

#  - name: update repository index
#    ansible.builtin.apt:
#    update_cache: yes

  - name: install apache2 package
    ansible.builtin.apt:
      name: apache2
      state: latest
    when: ansible_distribution == "ubuntu"

  - name: install support for php
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest
#    when: ansible_distribution == "ubuntu"

# Fedora

#  - name: update repository index
#    ansible.builtin.dnf:
#    update_cache: yes

  - name: install httpd package
    ansible.builtin.dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Fedora"

  - name: install support for php
    ansible.builtin.dnf:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Fedora"
