---

-hosts: all
become: true
tasks:
  - name: Install HTTPD package
     ansible.builtin.yum:
       name: httpd
       state: present

  - name: Ensure HTTPD service is started and enabled
     ansible.builtin.service:
       name: httpd
       state: started
       enabled: yes
